apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tools-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: tools.murmurations.developers
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: {{ .Values.name }}-service
                port:
                  number: {{ .Values.service.port }}
